var Version01 = {
  prefix: "extensions.zenotes.",
  data: {
    "paraphrase-custom-prompt": { key: "paraphrase-custom-prompt", encrypt: false },
    "cell-custom-prompt": { key: "cell-custom-prompt", encrypt: false },
    "row-custom-prompt": { key: "row-custom-prompt", encrypt: false },
    "table-custom-prompt": { key: "table-custom-prompt", encrypt: false },
    "vertical-table": { key: "vertical-table", encrypt: false },
    "bg-opacity": { key: "bg-opacity", encrypt: false },
    "header-size": { key: "header-size", encrypt: false },
    "column-width": { key: "column-width", encrypt: false },
    "font-size": { key: "font-size", encrypt: false },
    "font-family": { key: "font-family", encrypt: false },
    "custom-font-family": { key: "custom-font-family", encrypt: false },
    "html-filter": { key: "html-filter", encrypt: false },
    "html-filter-replacement": { key: "html-filter-replacement", encrypt: false },
    "dropbox-refresh-token": { key: "dropbox-refresh-token", encrypt: true },
    "dropbox-client-id": { key: "dropbox-client-id", encrypt: true },
    "dropbox-client-secret": { key: "dropbox-client-secret", encrypt: true },
    "dropbox-target-user": { key: "dropbox-target-user", encrypt: false },
    "dropbox-ms-per-file": { key: "dropbox-ms-per-file", encrypt: false },
    "notes-add-links": { key: "notes-add-links", encrypt: false },
    "bard-api-key": { key: "gemini-api-key", encrypt: true },
    "bard-model": { key: "gemini-model", encrypt: false },
    "bard-prompt": { key: "gemini-user-prompt", encrypt: false },
    "openai-api-key": { key: "openai-api-key", encrypt: true },
    "openai-model": { key: "openai-model", encrypt: false },
    "openai-max-token": { key: "openai-max-token", encrypt: false },
    
    "custom-api-url": { key: "custom-ai-url", encrypt: false },
    "custom-api-key": { key: "custom-ai-api-key", encrypt: true },
    "custom-api-model": { key: "custom-ai-model", encrypt: false },
    
    "custom-api-headers": { key: "custom-api-headers", encrypt: false },
    "custom-api-payload": { key: "custom-api-payload", encrypt: false },
    "custom-api-translator": { key: "custom-ai-format", encrypt: false },
    
    "load-settings": { key: "load-settings", encrypt: false },
    "display-and": { key: "display-and", encrypt: false },
    "display-etal": { key: "display-etal", encrypt: false },
    "load-on-change": { key: "load-on-change", encrypt: false },
    "remove-menu": { key: "remove-menu", encrypt: false },
    "tesseract-path": { key: "tesseract-path", encrypt: false },
    "tesseract-language": { key: "tesseract-language", encrypt: false },
    "target-language": { key: "translation-language", encrypt: false },
    "deepl-api-key": { key: "deepl-api-key", encrypt: true },
    "google-translate-key": { key: "google-translate-api-key", encrypt: true }
  }
}