# Gemfile

source "https://rubygems.org"

# Use the specific version of Jekyll compatible with GitHub Pages
gem "jekyll", "3.10.0"

# Use GitHub Pages gem (which will install the correct Jekyll version)
gem "github-pages", "~> 232", group: :jekyll_plugins

# Use the remote theme plugin to load themes from GitHub
gem "jekyll-remote-theme"

# Optional: other plugins for enhancing functionality
gem "jekyll-feed", "~> 0.12"

# Optional: For Windows, to watch directories faster
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Optional: To handle time zones in Windows and JRuby environments
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Optional: For performance enhancements with JRuby
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
